DROP DATABASE IF EXISTS kittens;
CREATE DATABASE kittens;

\c kittens;

CREATE TABLE cats (
  ID SERIAL PRIMARY KEY,
  name VARCHAR,
  breed VARCHAR,
  age INTEGER,
  sex VARCHAR
);

INSERT INTO cats (name, breed, age, sex)
  VALUES  ('Sophia','Abyssinian','12','F'),
          ('Jackson','Aegean','16','M'),
          ('Emma','American Curl','6','F'),
          ('Aiden','American Bobtail','8','M'),
          ('Olivia','American Shorthair','13','F'),
          ('Lucas','American Wirehair','3','M'),
          ('Ava','Arabian Mau','1','F'),
          ('Liam','Australian Mist','20','M'),
          ('Mia','Asian','10','F'),
          ('Noah','Asian Semi-longhair','8','M'),
          ('Isabella','Balinese','7','F'),
          ('Ethan','Bambino','5','M'),
          ('Riley','Bengal','3','F'),
          ('Mason','Birman','13','M'),
          ('Aria','Bombay','19','F'),
          ('Caden','Brazilian Shorthair','19','M'),
          ('Zoe','British Semi-longhair','6','F'),
          ('Oliver','British Shorthair','13','M'),
          ('Charlotte','British Longhair','14','F'),
          ('Elijah','Burmese','11','M'),
          ('Lily','Burmilla','1','F'),
          ('Grayson','California Spangled','1','M'),
          ('Layla','Chantilly-Tiffany','1','F'),
          ('Jacob','Chartreux','13','M'),
          ('Amelia','Chausie','20','F'),
          ('Michael','Cheetoh','17','M'),
          ('Emily','Colorpoint Shorthair','8','F'),
          ('Benjamin','Cornish Rex','4','M'),
          ('Madelyn','Manx Longhair','17','F'),
          ('Carter','Cyprus','11','M'),
          ('Aubrey','Devon Rex','9','F'),
          ('James','Donskoy','17','M'),
          ('Adalyn','Dragon Li','9','F'),
          ('Jayden','Dwarf cat','3','M'),
          ('Madison','Egyptian Mau','3','F'),
          ('Logan','European Shorthair','15','M'),
          ('Chloe','Exotic Shorthair','2','F'),
          ('Alexander','Foldex','9','M'),
          ('Harper','German Rex','7','F'),
          ('Caleb','Havana Brown','20','M'),
          ('Abigail','Highlander','19','F'),
          ('Ryan','Himalayan','15','M'),
          ('Aaliyah','Japanese Bobtail','3','F'),
          ('Luke','Javanese','12','M'),
          ('Avery','Kurilian Bobtail','17','F'),
          ('Daniel','Khao Manee','18','M'),
          ('Evelyn','Korat','1','F'),
          ('Jack','Korean Bobtail','5','M'),
          ('Kaylee','Korn Ja','5','F'),
          ('William','Kurilian Bobtail','17','M'),
          ('Ella','LaPerm','20','F'),
          ('Owen','Lykoi','8','M'),
          ('Ellie','Maine Coon','1','F'),
          ('Gabriel','Manx','12','M'),
          ('Scarlett','Mekong Bobtail','19','F'),
          ('Matthew','Minskin','10','M'),
          ('Arianna','Munchkin','4','F'),
          ('Connor','Nebelung','3','M'),
          ('Hailey','Napoleon','1','F'),
          ('Jayce','Norwegian Forest cat','18','M'),
          ('Nora','Ocicat','15','F'),
          ('Isaac','Ojos Azules','7','M'),
          ('Addison','Oregon Rex','14','F'),
          ('Sebastian','Oriental Bicolor','6','M'),
          ('Brooklyn','Oriental Shorthair','2','F'),
          ('Henry','Oriental Longhair','19','M'),
          ('Hannah','PerFold','4','F'),
          ('Muhammad','Persian','7','M'),
          ('Mila','Peterbald','11','F'),
          ('Cameron','Pixie-bob','1','M'),
          ('Leah','Raas','11','F'),
          ('Wyatt','Ragamuffin','16','M'),
          ('Elizabeth','Ragdoll','11','F'),
          ('Dylan','Russian Blue','7','M'),
          ('Sarah','Russian White','6','F'),
          ('Nathan','Russian Black','7','M'),
          ('Eliana','Russian Tabby','9','F'),
          ('Nicholas','Sam Sawet','18','M'),
          ('Mackenzie','Savannah','18','F'),
          ('Julian','Scottish Fold','2','M'),
          ('Peyton','Selkirk Rex','2','F'),
          ('Eli','Serengeti','15','M'),
          ('Maria','Serrade petit','12','F'),
          ('Levi','Siamese','9','M'),
          ('Grace','Siberian','10','F'),
          ('Isaiah','Singapura','7','M'),
          ('Adeline','Snowshoe','9','F'),
          ('Landon','Sokoke','14','M'),
          ('Elena','Somali','12','F'),
          ('David','Sphynx','14','M'),
          ('Anna','Suphalak','12','F'),
          ('Christian','Thai','3','M'),
          ('Victoria','Thai Lilac','20','F'),
          ('Andrew','Tonkinese','15','M'),
          ('Camilla','Toyger','6','F'),
          ('Brayden','Turkish Angora','13','M'),
          ('Lillian','Turkish Van','20','F'),
          ('John','Ukrainian Levkoy','9','M');
